config:
  assrDir: "../assr-2/"
  gitlabProject: 366
  targetBranch: "master"
  gitlabBaseURL: "http://gitlab.k8s.alfa.link/api/v4"
  gitlabToken: ${GITLAB_TOKEN}
  testerId: 557

tasks:
  ALFABANKRU-00:
    - "@alfabank/main-carousel"